FROM python:3.9-bullseye

RUN python3 -m pip install --upgrade pip && pip install requests==2.* pandas==2.* --no-cache-dir 

COPY getdata.py ./
RUN chmod a+x /getdata.py

ENTRYPOINT ["python3", "./getdata.py"]